#When infested with a Mutant X potion, what mutant mob should the target transform into. Otherwise the target will ony explode and take damage.
#Format for every entry is "<namespace>:<path>,<namespace>:<path>" with the second id representing the mutant. Namespace may be omitted to use "minecraft" by defau>
mutant_x_conversions = ["minecraft:creeper,mutantmonsters:mutant_creeper", "minecraft:enderman,mutantmonsters:mutant_enderman", "minecraft:skeleton,mutantmonsters:>
#Weight for mutant creeper spawns as a percentage of the vanilla creeper spawn weight. Mutants can spawn in every biome and dimension where their vanilla counterpa>
#Range: 0.0 ~ 1.0
mutant_creeper_spawn_weight = 0.50
#Weight for mutant enderman spawns as a percentage of the vanilla enderman spawn weight. Mutants can spawn in every biome and dimension where their vanilla counter>#Range: 0.0 ~ 1.0
mutant_enderman_spawn_weight = 0.50
#Weight for mutant skeleton spawns as a percentage of the vanilla skeleton spawn weight. Mutants can spawn in every biome and dimension where their vanilla counter>#Range: 0.0 ~ 1.0
mutant_skeleton_spawn_weight = 0.50
#Weight for mutant zombie spawns as a percentage of the vanilla zombie spawn weight. Mutants can spawn in every biome and dimension where their vanilla counterpart>#Range: 0.0 ~ 1.0
mutant_zombie_spawn_weight = 0.50