on:
  push:
    branches:
      - development

jobs:
  release-on-push:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: rymndhng/release-on-push-action@master
        with:
          bump_version_scheme: patch
          use_github_release_notes: true
  build-client-files:
    needs: release-on-push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Zip Folder
        run: zip -r ${{ github.event.repository.name }}.zip ./client/

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ${{ github.event.repository.name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}